# Generated by Django 5.0.3 on 2024-08-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_level',
            field=models.IntegerField(choices=[(25, '25'), (30, '30'), (35, '35'), (40, '40')], default=25),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='required_intake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
